[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["Bartosz Nowak <sztosz.github@gmail.com>"]

[dependencies]
diesel = { version = "0.15.0", features = ["postgres"] }
diesel_codegen = { version = "0.15.0", features = ["postgres"] }
dotenv = "0.9.0"
